Phil reported what looks like a missing #include <unistd.h>. Added the missing file & hoping.
make[3]: Entering directory `/home/ubuntu/ginger-0.8/build/ginger/apps/file2gnx/cpp'
g++ -DINSTALL_BIN='"/usr/local/bin"' -DINSTALL_LIB='"/usr/local/share/ginger"' -DINSTALL_TOOL='"/usr/local/libexec/ginger"' -g -I../hpp -I../../libgng/hpp -Wall -Wnon-virtual-dtor    -c -o file2gnx.o file2gnx.cpp
file2gnx.cpp: In function ‘void run(std::string, std::string)’:
file2gnx.cpp:43:42: error: ‘execl’ was not declared in this scope
make[3]: *** [file2gnx.o] Error 1